In [16]:
import numpy as np
import pandas as pd

In [2]:
X = np.array([[1], [2], [3]])
Y = np.array([[1], [2], [2]])

In [9]:
X = np.hstack([np.ones((3,1)), X])

In [14]:
X_EST = np.dot(np.linalg.inv(np.dot(X.T, X)), np.dot(X.T, Y))

In [15]:
X_EST

array([[0.66666667],
       [0.5       ]])

In [22]:
# load the road.txt data
url = 'https://raw.githubusercontent.com/eggplantbren/STATS331/master/Code/Regression/road.txt'
df = pd.read_csv(url, sep='\t')

In [33]:
data = df.values
(m,n) = data.shape

In [35]:
X = np.reshape(data[: , 0], (m,1))
Y = np.reshape(data[: ,1], (m,1))

In [38]:
# taking care of bias term
X = np.hstack([np.ones((m,1)), X])

In [42]:
X_EST = np.dot(np.linalg.inv(np.dot(X.T, X)), np.dot(X.T,Y))

In [43]:
X_EST

array([[578.88550219],
       [ -3.04079336]])

In [44]:
from sklearn import linear_model


In [45]:
lin_obj = linear_model.LinearRegression()

In [46]:
lin_obj.fit(np.reshape(data[: , 0], (m,1)), np.reshape(data[: ,1], (m,1)))

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None,
         normalize=False)

In [47]:
lin_obj.coef_

array([[-3.04079336]])

In [48]:
lin_obj.intercept_

array([578.88550219])

In [54]:
lin_obj.score(np.reshape(data[: , 0], (m,1)), np.reshape(data[: ,1], (m,1)))

0.6279850286877784