In [46]:
import numpy as np
from sklearn import datasets, preprocessing, model_selection
from sklearn import linear_model

In [3]:
# load the data
boston_data = datasets.load_boston()

In [5]:
X = boston_data.data

In [9]:
(m, n) = X.shape

In [10]:
Y = np.reshape(boston_data.target, (m,1))

In [14]:
# data normalization, 0 mean and standard deviation
X = preprocessing.scale(X)


In [18]:
# split the data into train and test
X_train, X_test, Y_train, Y_test = model_selection.train_test_split(X, Y, test_size=.3)

In [29]:
(m_train, n_train) = X_train.shape

In [38]:
def cost_function(X, Y, theta):
    return (1/2*X.shape[0])*np.sum(np.square(np.dot(X, theta)- Y), axis=0)[0]

In [51]:
def batch_gradient_descent(X, Y, learning_rate=.01, error=1e-9):
    (m, n) = X.shape
    # bias term column
    X = np.hstack([np.ones((m,1)), X])
    
    theta = np.ones((n+1,1))
    
    no_of_iter = 0
    
    while True:
        cost_prev = cost_function(X, Y, theta)
        theta -= (learning_rate/m)*(np.dot(X.T, np.dot(X, theta)-Y))
        cost_curr = cost_function(X, Y, theta)
        
        if abs(cost_prev-cost_curr)<error:
            break
        no_of_iter += 1
        
    return (theta, no_of_iter)
        
        

In [52]:
(theta, no_of_iter) = batch_gradient_descent(X_train, Y_train)

In [53]:
theta

array([[22.50329436],
       [-0.93440024],
       [ 1.40610115],
       [-0.02975095],
       [ 0.58342958],
       [-1.82662665],
       [ 2.40631058],
       [ 0.54764729],
       [-2.93834915],
       [ 2.88986609],
       [-2.63457155],
       [-1.8718151 ],
       [ 0.65629164],
       [-3.91190551]])

In [47]:
lgr = linear_model.LinearRegression()

In [48]:
lgr.fit(X_train, Y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None,
         normalize=False)

In [49]:
lgr.intercept_

array([22.50329429])

In [50]:
lgr.coef_

array([[-0.93440087,  1.40610204, -0.02974763,  0.58342899, -1.82662689,
         2.40630984,  0.54764786, -2.9383485 ,  2.88987738, -2.63458381,
        -1.87181573,  0.65629176, -3.91190591]])