In [176]:
from sklearn import datasets, linear_model, model_selection
import numpy as np
from sklearn.feature_selection import RFE

In [177]:
data = datasets.load_boston()

In [178]:
X = data.data

In [179]:
(m,n) = X.shape

In [180]:
Y = data.target

# RFE algorithm to get the best features, recursively removes features 

In [104]:
best_score = 0

In [105]:
no_of_optimal_features = 0

In [106]:
ranking = None
support = None

In [130]:
X_train, X_test, Y_train, Y_test = model_selection.train_test_split(X, Y, test_size=.3)

In [131]:
for i in range(n):
    model = linear_model.LinearRegression()
    rfe = RFE(model, i+1)
    X_train_rfe = rfe.fit_transform(X_train, Y_train)
    X_test_rfe = rfe.transform(X_test)
    
    model.fit(X_train_rfe, Y_train)
    score  = model.score(X_test_rfe, Y_test)
    if score>best_score:
        no_of_optimal_features = i+1;
        best_score = score
        support = rfe.support_
        ranking = rfe.ranking_
    

In [132]:
best_score

0.7627663748582422

In [133]:
no_of_optimal_features

12

In [134]:
print(support)

[ True  True  True  True  True  True False  True  True  True  True  True
  True]


In [135]:
ranking

array([1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1])

In [181]:
from sklearn.feature_selection import RFECV

In [182]:
model = linear_model.LinearRegression()

In [210]:
rfecv = RFECV(model, step=1, min_features_to_select=1, cv=3)

In [211]:
rfecv = rfecv.fit(X, Y)

In [212]:
rfecv.ranking_

array([4, 6, 5, 1, 1, 1, 9, 1, 3, 7, 1, 8, 2])

In [213]:
rfecv.support_

array([False, False, False,  True,  True,  True, False,  True, False,
       False,  True, False, False])

In [214]:
import pandas as pd

In [215]:
t = pd.Series(rfecv.support_, index=data.feature_names)

In [216]:
t[t==True].index

Index(['CHAS', 'NOX', 'RM', 'DIS', 'PTRATIO'], dtype='object')

In [ ]:
model = linear_model.LinearRegression()
rfe = RF