In [93]:
import numpy as np
import pandas as pd
from sklearn import preprocessing

In [94]:
data = np.array([
    [1,1],
    [2,2],
    [3,2]
])

In [95]:
(m,n) = data.shape

In [96]:
target = np.reshape(data[:, -1], (m,1))

In [97]:
features = np.reshape(data[: , 0], (m,1))

In [98]:
scaled_features = preprocessing.scale(features.astype(float), axis=0)

In [99]:
A = np.hstack([np.ones((m,1)), features])

In [100]:
parameters = np.dot(np.linalg.inv(np.dot(A.T, A)),np.dot(A.T, target))

In [101]:
parameters

array([[0.66666667],
       [0.5       ]])

In [102]:
_A = np.hstack([np.ones((m,1)), scaled_features])

In [103]:
_parameters = np.dot(np.linalg.inv(np.dot(_A.T, _A)),np.dot(_A.T, target))

In [104]:
_parameters

array([[1.66666667],
       [0.40824829]])

In [40]:
from sklearn import linear_model

In [45]:
ln = linear_model.LinearRegression(normalize=True)

In [46]:
ln.fit(features, target)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=True)

In [47]:
ln.coef_

array([[0.5]])

In [48]:
ln.intercept_

array([0.66666667])

In [54]:
target

array([[1],
       [2],
       [2]])

In [80]:
# let new point be 4
mu = features.mean()
sd = features.std()

In [84]:
new_point = (4-mu)/sd

In [85]:
x_test = np.array([
    [1, new_point],
])

In [87]:
np.dot(x_test, parameters)

array([[1.89141154]])

In [88]:
np.dot(x_test, _parameters)

array([[2.66666667]])

In [108]:
get_back_features = scaled_features*sd + mu

In [109]:
get_back_features

array([[1.],
       [2.],
       [3.]])