In [46]:
from sklearn import datasets, preprocessing, model_selection, linear_model
import numpy as np

In [47]:
# load boston housing dataset
dataset = datasets.load_boston()

In [48]:
X = dataset.data

In [49]:
(m,n) = X.shape

In [50]:
Y = np.reshape(dataset.target, (m,1))

In [51]:
# split the data into train and test
X_train, X_test, Y_train, Y_test = model_selection.train_test_split(X, Y, test_size=.3)

# Scale the data

In [52]:
#X_train_scaled = preprocessing.scale(X_train)
X_train_scaled = X_train - X_train.mean()

In [53]:
lgr = linear_model.LinearRegression()
lgr_for_scaled = linear_model.LinearRegression() # may be dumb to create two objects, but its okay

In [54]:
lgr.fit(X_train, Y_train)
lgr_for_scaled.fit(X_train_scaled, Y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None,
         normalize=False)

In [55]:
lgr.intercept_

array([30.82133483])

In [56]:
lgr_for_scaled.intercept_

array([-945.81248814])

In [57]:
lgr.coef_

array([[-1.00042360e-01,  4.22149609e-02,  5.91135965e-02,
         2.68408188e+00, -1.86804097e+01,  4.39369599e+00,
         5.47047133e-03, -1.28630193e+00,  2.95789360e-01,
        -1.26035935e-02, -9.84796513e-01,  1.16187905e-02,
        -4.35816555e-01]])

In [58]:
lgr_for_scaled.coef_

array([[-1.00042360e-01,  4.22149609e-02,  5.91135965e-02,
         2.68408188e+00, -1.86804097e+01,  4.39369599e+00,
         5.47047133e-03, -1.28630193e+00,  2.95789360e-01,
        -1.26035935e-02, -9.84796513e-01,  1.16187905e-02,
        -4.35816555e-01]])

Scaled features have differnt intercept value in parameters but same coefficent values