In [12]:
import numpy as np
import matplotlib.pyplot as plt
from sklearn import preprocessing, model_selection
import pandas as pd

In [27]:
# Load the data
df = pd.read_excel('srilaxmi.xlsx')

In [28]:
(m,n) = df.shape

In [29]:
dt = df.values

In [30]:
features = dt[:, :-1]

In [31]:
target = np.reshape(dt[:, n-1], (m,1))

In [32]:
data = np.hstack([np.ones((m,1)), features])

In [33]:
x_train, x_test, y_train, y_test = model_selection.train_test_split(data, target, test_size=.3)

In [34]:
parameters = np.dot(np.linalg.inv(np.dot(x_train.T, x_train)), np.dot(x_train.T, y_train))

In [35]:
parameters

array([[1154.12748122],
       [ -23.32233302],
       [  33.02184293],
       [ -14.51577195]])

In [45]:
predict_for = np.array([
    [1, 9, 40, 5]
])

In [46]:
np.dot(predict_for, parameters)

array([[2192.52134148]])

In [38]:
predict_for

array([[ 5, 35,  1]])